"""add genres, score, rank, popularity, season, year to anime

Revision ID: 440f70a8f941
Revises: bd082f3f8d60
Create Date: 2026-08-14 02:56:32.108292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440f70a8f941'
down_revision: Union[str, Sequence[str], None] = 'bd082f3f8d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('anime_genres',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'genre_id')
    )
    op.add_column('anime', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('anime', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('anime', sa.Column('popularity', sa.Integer(), nullable=True))
    op.add_column('anime', sa.Column('season', sa.String(length=10), nullable=True))
    op.add_column('anime', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'year')
    op.drop_column('anime', 'season')
    op.drop_column('anime', 'popularity')
    op.drop_column('anime', 'rank')
    op.drop_column('anime', 'score')
    op.drop_table('anime_genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
