"""add rating, duration, type, trailer fields; genre category

Revision ID: 5b3ddae72dba
Revises: 440f70a8f941
Create Date: 2026-08-18 11:09:45.886166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3ddae72dba'
down_revision: Union[str, Sequence[str], None] = '440f70a8f941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('rating', sa.String(length=50), nullable=True))
    op.add_column('anime', sa.Column('duration', sa.String(length=30), nullable=True))
    op.add_column('anime', sa.Column('type', sa.String(length=20), nullable=True))
    op.add_column('anime', sa.Column('trailer_youtube_id', sa.String(length=20), nullable=True))
    op.add_column('anime', sa.Column('trailer_embed_url', sa.String(length=255), nullable=True))
    op.add_column('genres', sa.Column('category', sa.String(length=20), nullable=False, server_default='genre'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genres', 'category')
    op.drop_column('anime', 'trailer_embed_url')
    op.drop_column('anime', 'trailer_youtube_id')
    op.drop_column('anime', 'type')
    op.drop_column('anime', 'duration')
    op.drop_column('anime', 'rating')
    # ### end Alembic commands ###
