"""add streaming_links to anime

Revision ID: f56276c32ef3
Revises: 5b3ddae72dba
Create Date: 2026-08-18 11:38:25.450022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f56276c32ef3'
down_revision: Union[str, Sequence[str], None] = '5b3ddae72dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('streaming_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'streaming_links')
    # ### end Alembic commands ###
